Controllers/AssistantFormController.cs
using System.Net;
using meethub.Models;
using Microsoft.AspNetCore.Mvc;
using PdfSharpCore.Drawing;
using PdfSharpCore.Pdf;

namespace meethub.Controllers;

public class AssistantFormController : Controller
{
    private readonly MeethubdbContext _context;
    private readonly IWebHostEnvironment _hostEnvironment;

    public AssistantFormController(MeethubdbContext context, IWebHostEnvironment hostEnvironment)
    {
        _context = context;
        _hostEnvironment = hostEnvironment;
    }

    // VISTA FORMULARIO
    [Route("AssistantForm/Form/{id?}")]
    public IActionResult Form(int id)
    {
        var evento = _context.Events.FirstOrDefault(e => e.IdEvent == id);
        if (evento == null)
        {
            return RedirectToAction("Login", "User"); // Manejar el caso en el que no se encuentre el evento con el id especificado
        }

        return View(evento);
    }

    // VISTA REGISTRO EXITOSO
    public IActionResult Success(int AssistantId)
    {
        ViewBag.AssistantId = AssistantId;
        return View();
    }

    // VISTA REGISTRO FALLIDO
    public IActionResult Failed()
    {
        return View();
    }

    [HttpPost]
    public IActionResult DeleteTempData(string key)
    {
        TempData.Remove(key);
        return Ok();
    }

    // METODO REGISTRAR ASISTENTE
    [HttpPost]
    public async Task<IActionResult> RegisterToEvent(String nombre, String apellidos, String email, String telefono, int id)
    {
        // COMPROBAR TIPO DE EVENTO
        var evento = _context.Events.FirstOrDefault(e => e.IdEvent == id);
        Boolean aprobacion = true;
        if (evento != null)
        {
            if (evento.Tipo == "invitacion")
            {
                aprobacion = false;
            }
        }

        // crear modelo del nuevo asistente
        var newAssistant = new Assistant
        {
            IdEvent = id,
            Nombre = nombre,
            Apellidos = apellidos,
            Email = email,
            Telefono = telefono,
            Aprobado = aprobacion,
            Confirmado = false,
            QrCode = ""
        };

        // Comprobar si el asistente ya se ha registrado al evento
        var asistenteRepetido = _context.Assistants.FirstOrDefault(a => a.Email == newAssistant.Email && a.IdEvent == id);

        if (asistenteRepetido == null)
        {
            try
            {
                // Guardar el nuevo asistente en la base de datos
                _context.Assistants.Add(newAssistant);
                _context.SaveChanges();

                // CREACION DE QR
                String qrUrl = "https://chart.googleapis.com/chart?cht=qr&chs=200x200&chld=L|3&chl=" + newAssistant.IdAssistant;
                newAssistant.QrCode = qrUrl;
                _context.Assistants.Update(newAssistant);
                _context.SaveChanges();

                return RedirectToAction("Success", new { AssistantId = newAssistant.IdAssistant });
            }
            catch (Exception e)
            {
                return RedirectToAction("Failed");
            }
        }else{
            TempData["InvalidEmail"] = "Este email ya ha sido registrado a este evento.";
            return RedirectToAction("Form", new {id = id});
        }
    }

    // METODO GENERAR ENTRADA PDF
    public IActionResult GeneratePDF(int id)
    {
        var asistente = _context.Assistants.FirstOrDefault(a => a.IdAssistant == id);

        if (asistente != null)
        {
            var evento = _context.Events.FirstOrDefault(e => e.IdEvent == asistente.IdEvent);
            if (evento != null)
            {
                try
                {
                    // Crear un nuevo documento PDF
                    var document = new PdfDocument();

                    // Agregar una página al documento
                    var page = document.AddPage();

                    // Obtener el objeto XGraphics para dibujar en la página
                    var gfx = XGraphics.FromPdfPage(page);

                    // Fuente
                    int fontSize = 12;
                    var fontTitle = new XFont("Tahoma", fontSize, XFontStyle.Bold);
                    var fontContent = new XFont("Tahoma", fontSize);

                    gfx.TranslateTransform(0, 20);

                    // Logo
                    string logoPath = Path.Combine(_hostEnvironment.WebRootPath, "images", "logo.png");
                    XImage logoImage = XImage.FromFile(logoPath);
                    double logoWidth = 200;
                    double logoHeight = logoWidth * (logoImage.PixelHeight / (double)logoImage.PixelWidth);
                    gfx.DrawImage(logoImage, new XRect(10, 10, logoWidth, logoHeight));

                    // Datos del evento
                    gfx.TranslateTransform(0, 80);
                    gfx.DrawString("Datos del Evento:", fontTitle, XBrushes.Black, new XPoint(10, 10));
                    gfx.DrawString("Evento: " + evento.Titulo, fontContent, XBrushes.Black, new XPoint(10, 30));
                    gfx.DrawString("Dirección: " + evento.Direccion, fontContent, XBrushes.Black, new XPoint(10, 50));
                    gfx.DrawString("Fecha: " + evento.FechaInicio.ToString("dd/MM/yyyy HH:mm") + " - " + evento.FechaFin.ToString("dd/MM/yyyy HH:mm"), fontContent, XBrushes.Black, new XPoint(10, 70));

                    // Datos del asistente
                    gfx.DrawString("Datos del Asistente:", fontTitle, XBrushes.Black, new XPoint(10, 100));
                    gfx.DrawString("Nombre: " + asistente.Nombre, fontContent, XBrushes.Black, new XPoint(10, 120));
                    gfx.DrawString("Apellidos: " + asistente.Apellidos, fontContent, XBrushes.Black, new XPoint(10, 140));

                    // Obtener el código QR del asistente
                    var qrCodeUrl = asistente.QrCode;

                    // Cargar la imagen del código QR desde la URL
                    using (var webClient = new WebClient())
                    {
                        var qrImageData = webClient.DownloadData(qrCodeUrl);
                        using (var qrImageStream = new MemoryStream(qrImageData))
                        {
                            var qrImage = XImage.FromStream(() => qrImageStream);

                            // Especificar el tamaño de la página (A4 estándar)
                            var pageWidth = XUnit.FromCentimeter(21);
                            var pageHeight = XUnit.FromCentimeter(29.7);

                            // Calcular el tamaño y la posición de la imagen centrada
                            var maxWidth = pageWidth - XUnit.FromCentimeter(2);  // Ancho máximo de la página con un margen de 1 cm en cada lado
                            var maxHeight = pageHeight - XUnit.FromCentimeter(10);  // Alto máximo de la página con un margen de 5 cm en la parte superior

                            var aspectRatio = (double)qrImage.PixelWidth / qrImage.PixelHeight;
                            var width = Math.Min(maxWidth, qrImage.PixelWidth);
                            var height = width / aspectRatio;

                            if (height > maxHeight)
                            {
                                height = maxHeight;
                                width = height * aspectRatio;
                            }

                            var x = (pageWidth - width) / 2;  // Posición x centrada
                            var y = XUnit.FromCentimeter(5) + (maxHeight - height) / 2;  // Posición y centrada

                            gfx.DrawImage(qrImage, x, y, width, height);
                        }
                    }

                    // Guardar el documento en un MemoryStream
                    var memoryStream = new MemoryStream();
                    document.Save(memoryStream);
                    memoryStream.Seek(0, SeekOrigin.Begin);

                    // Devolver el archivo PDF
                    return File(memoryStream, "application/pdf", "entrada.pdf", true);
                }
                catch (Exception e)
                {
                    return RedirectToAction("Success", new { AssistantId = asistente.IdAssistant });
                }
            }
        }
        return RedirectToAction("Index", "home");
    }
}

Views/AssistantForm/Failed.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MeetHub</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">

    @{
        Layout = null;
    }

    <!-- CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/mystyles.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            background-image: url('/meethub/images/fondoprueba.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
            background-color: #e7e9ec;
        }

        #assistant-form label {
            color: #ababab;
        }
    </style>
</head>

<body class="vh-100">
    <div class="h-100 w-100 justify-content-center align-items-center flex-column d-flex py-5 px-3">
        <div class="p-4 d-flex rounded-5 bg-light align-items-center justify-content-center text-center"
            style="height: fit-content;">
            <span class="fw-bold fs-2 text-danger me-3">Hubo un error al registrarte al evento :(</span>
            <i class="bi bi-x-circle text-danger" style="font-size: 50px;"></i>
        </div>
        <span class="text-secondary fw-bold mt-3">Prueba a intentarlo de nuevo.</span>
    </div>

    <!-- SCRIPTS -->
    <script src="~/lib/fontawesome/fontawesome.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/myscripts.js"></script>
</body>

</html>

Views/AssistantForm/Form.cshtml
@model Event

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MeetHub</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">

    @{
        Layout = null;
    }

    <!-- CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/mystyles.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            background-image: url('/meethub/images/fondoprueba.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
            background-color: #e7e9ec;
        }

        #assistant-form label {
            color: #ababab;
        }
    </style>
</head>

<body class="vh-100">
    <div class="h-100 w-100 justify-content-center align-items-center d-flex py-5 px-3">
        <div class="d-flex flex-column rounded-5 bg-light align-items-center justify-content-center"
            style="width: 400px; height: fit-content;">
            @if (Model != null)
            {
                <div class="d-flex flex-column justify-content-center my-4" style="width: 300px;">
                    <span class="fw-bold fs-3 mb-2">@Model.Titulo</span>
                    <span class="fw-medium fs-5 mb-2">@Model.Descripcion</span>
                    <div class="w-100 d-flex mb-2">
                        <i class="bi bi-clock-fill" style="color: #ff9d46;"></i>
                        <span class="ms-2 me-1">@Model.FechaInicio.ToString("dd/MM/yyyy HH:mm")</span>
                        -<span class="ms-1">@Model.FechaFin.ToString("dd/MM/yyyy HH:mm")</span>
                    </div>
                    <div class="d-flex w-100">
                        <i class="bi bi-geo-alt-fill" style="color: #ff9d46;"></i>
                        <span class="fw-semibold fs-6 ms-2">@Model.Direccion</span>
                    </div>
                </div>
            }
            <form asp-action="RegisterToEvent" method="post" class="mb-4 needs-validation" id="assistant-form"
                novalidate style="width: 300px;">
                <input type="hidden" name="id" value="@Model.IdEvent" />
                <div class="form-floating mb-3">
                    <input name="nombre" type="text" class="form-control" id="assistant-nombre" placeholder="Nombre"
                        required>
                    <label for="assistant-nombre">Nombre</label>
                    <div class="invalid-feedback">
                        Escribe tu nombre.
                    </div>
                </div>

                <div class="form-floating mb-3">
                    <input name="apellidos" type="text" class="form-control" id="assistant-apellidos"
                        placeholder="Apellidos" required>
                    <label for="assistant-apellidos">Apellidos</label>
                    <div class="invalid-feedback">
                        Escribe tus apellidos.
                    </div>
                </div>

                <div class="form-floating mb-3">
                    <input name="email" type="email" class="form-control" id="floatingInput"
                        placeholder="name@example.com" required>
                    <label for="floatingInput">Correo electrónico</label>
                    <div class="invalid-feedback">
                        Introduce un correo electrónico válido.
                    </div>
                </div>

                <div class="form-floating mb-3">
                    <input name="telefono" type="number" class="form-control" id="assistant-telefono"
                        placeholder="635372277" required>
                    <label for="assistant-telefono">Teléfono de contacto</label>
                    <div class="invalid-feedback">
                        Introduce un número de teléfono válido.
                    </div>
                </div>

                <div class="d-flex w-100">
                    <button type="submit" class="btn btn-outline-success ms-auto">Enviar</button>
                </div>
            </form>
        </div>
    </div>

    <div class="modal fade" id="InvalidEmailModal" tabindex="-1" aria-labelledby="InvalidEmailModalLabel"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="InvalidEmailModalLabel">Alerta</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    @TempData["InvalidEmail"]
                </div>
            </div>
        </div>
    </div>

    <!-- SCRIPTS -->
    <script src="~/lib/fontawesome/fontawesome.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/myscripts.js"></script>

    @if (TempData["InvalidEmail"] != null)
    {
        <script>
            function deleteTempData(key) {
                $.ajax({
                    type: "POST",
                    url: "@Url.Action("DeleteTempData", "AssistantForm")",
                    data: { key: key },
                    success: function () { },
                    error: function () { }
                });
            }

            $(document).ready(function () {
                $('#InvalidEmailModal').modal('show');
                deleteTempData("InvalidEmail");
            });
        </script>
    }

    <script>
        $(document).ready(() => {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            const forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                    if (!form.checkValidity()) {
                        event.preventDefault();
                        event.stopPropagation();
                    }

                    form.classList.add('was-validated');
                }, false);
            });
        });

        $(document).ready(function () {
            $('#assistant-telefono').on('input', function () {
                var telefono = $(this).val();
                var regex = /^\d{9}$/;

                if (regex.test(telefono)) {
                    $(this).removeClass('is-invalid');
                } else {
                    $(this).addClass('is-invalid');
                }
            });

            $('#assistant-form').on('submit', function (event) {
                var telefono = $('#assistant-telefono').val();
                var regex = /^\d{9}$/;

                if (!regex.test(telefono)) {
                    $('#assistant-telefono').addClass('is-invalid');
                    event.preventDefault(); // Evita que se envíe el formulario
                }
            });
        });
    </script>

</body>

</html>

Views/AssistantForm/Success.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MeetHub</title>
    <link rel="icon" type="image/x-icon" href="~/favicon.ico">

    @{
        Layout = null;
    }

    <!-- CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/mystyles.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        html,
        body {
            height: 100%;
        }

        body {
            background-image: url('/meethub/images/fondoprueba.jpg');
            background-repeat: no-repeat;
            background-size: cover;
            background-position: center center;
            background-color: #e7e9ec;
        }

        #assistant-form label {
            color: #ababab;
        }
    </style>
</head>

<body class="vh-100">
    <div class="h-100 w-100 justify-content-center align-items-center flex-column d-flex py-5 px-3">
        <div class="p-4 d-flex rounded-5 bg-light align-items-center justify-content-center text-center"
            style="height: fit-content;">
            <span class="fw-bold fs-2 text-success me-3">Te has registrado al evento correctamente.</span>
            <i class="bi bi-check-circle text-success" style="font-size: 50px;"></i>
        </div>
        <div class="d-flex mt-3">
            <a href="@Url.Action("GeneratePDF", "AssistantForm", new { id = ViewBag.AssistantId })" class="btn btn-primary">Descargar Entrada PDF</a>
        </div>
        <span class="text-secondary fw-bold mt-3">Ya puedes cerrar esta ventana.</span>
    </div>

    <!-- SCRIPTS -->
    <script src="~/lib/fontawesome/fontawesome.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/myscripts.js"></script>

</body>

</html>